if getActivatedMods():contains("Smoker") then
    Events.OnGameBoot.Add(function()
        local function setRequireLighter(itemName, setRequire)
            ScriptManager.instance:getItem(itemName):DoParam("RequireInHandOrInventory = " .. setRequire)
        end

        setRequireLighter("MoreSmokes.MSCigarette", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Cigarillo", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.MSCigar", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        
        setRequireLighter("MoreSmokes.JointNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointIndigoFog", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.BluntNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.BluntPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.BluntSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.BluntBackwoods", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
    
        setRequireLighter("MoreSmokes.SpliffNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SpliffPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SpliffSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")

        setRequireLighter("MoreSmokes.CigarPlus", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointNorthernLightsPlus", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointPurpleHazePlus", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.JointSourDieselPlus", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")

        setRequireLighter("MoreSmokes.SmokePipe1Tobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe2Tobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe3Tobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassBlueTobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassGreenTobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassYellowTobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipePinkTobacco", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah1ShishaWatermelon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah1ShishaOrange", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah1ShishaLemon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2ShishaWatermelon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2ShishaOrange", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2ShishaLemon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3ShishaWatermelon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3ShishaOrange", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3ShishaLemon", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
    
        setRequireLighter("MoreSmokes.SmokePipe1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassBlueNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassGreenNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassYellowNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipePinkNorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassBluePurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassGreenPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassYellowPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipePinkPurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipe3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassBlueSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassGreenSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipeGlassYellowSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.SmokePipePinkSourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
    
        setRequireLighter("MoreSmokes.Hookah1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Hookah3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
    
        setRequireLighter("MoreSmokes.Bong1v1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v4NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v4NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v4NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v1NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v2NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v3NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v4NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong5NorthernLights", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v4PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v4PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v4PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v1PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v2PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v3PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v4PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong5PurpleHaze", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong1v4SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong2v4SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong3v4SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v1SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v2SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v3SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong4v4SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
        setRequireLighter("MoreSmokes.Bong5SourDiesel", "SM.SMFoil_Lighter/Base.Matches/SM.Matches/Base.Lighter")
    end);
else
    return
end